### ISSUE TITLE
Pagerduty scaffolder actions

### ISSUE THREAD

**Issue by Alok650** [PagerDuty/backstage-plugin#35]
**Is your feature request related to a problem? Please describe.**

The problem that I am trying to solve is of new service onboarding, i.e. when a new service gets created, I want to create a new PD service for it based on the PD team provided by user input

**Describe the solution you'd like**
 
We can have a set of actions like
1. pagerduty:create:service - which creates a pagerduty service
2. pagerduty:integrate:*- which integrates the pagerduty service with the other third party services like Datadog, signalFX

**Comment by t1agob** [comment]
Hi @Alok650. Thanks for raising this issue. 

I'm actively looking into this. Currently our recommendation - as a workaround - is to use the APIs to create services or to bring the PagerDuty Terraform provider into your project templates but we know it is not a clean solution. 

The scaffolder actions your propose make total sense to simplify the developer experience and we will have an implementation for creating new services quickly I believe.

For the integration part it is a bit more complex because we need implementations for different providers. Can you tell us what you use to maintain your service catalog currently? That will help us prioritise.

**Comment by Alok650** [comment]
Hi @t1agob Thanks for looking into this

In the short term, I'll write custom actions using the PD APIs for creation, modification.

For integrations, we currently are trying to do this with:
- Datadog
- Coralogix
- AWS
- SignalFX

**Comment by t1agob** [comment]
Hi @Alok650!

After further analysis of your feature request I am going to break it into two separate issues to reduce the scope of each action (#41, #42). 

To implement scaffolder actions it is recommended that we use a backend. This is going to be introduced to the plugin as part of the work of #37. 

This issue will be closed now and followed up on #41 and #42.
